name: Build and Upload Extension

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
            version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install
      - name: Build Chrome Extension
        run: make build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: latestBuild.zip
          path: latestBuild.zip